Find the main class to run

diff --git a/bin/grader b/bin/grader
--- a/bin/grader
+++ b/bin/grader
@@ -2,8 +2,16 @@
 
 
 # $1 = Assignment name
-rm -rf /tmp/$1.zip /tmp/$1
-cp ~/Downloads/submissions.zip /tmp/$1.zip
+subzip=$HOME/Downloads/submissions.zip
+if [ -z "$1" ]; then
+    echo "$0 <assignment>"
+    echo "    Specify the name of the assignment"
+    echo "    Assumes $subzip"
+    exit 2
+fi
+test -f /tmp/$1.zip && rm -rf /tmp/$1.zip 
+test -d /tmp/$1 &&  rm -rf /tmp/$1
+cp $subzip /tmp/$1.zip
 mkdir /tmp/$1
 cd /tmp/$1
 unzip /tmp/$1.zip
@@ -11,25 +19,54 @@ unzip /tmp/$1.zip
 
 for f in *
 do
+
+    echo START $f
     cd /tmp/$1
     d=`echo  $f | awk -F_ '{print $1}'`
-    ff=`echo  $f | awk -F_ '{print $4}'`
-    mkdir $d
     pwd
-    mv $f $d/$ff
+    for fil in `ls ${d}_[0-9]*_[0-9]*_*`; do
+	id=`echo  $fil | awk -F_ '{print $2 "_" $3}'`
+	ff=`echo  $fil | awk -F_ '{print $4}'`
+	echo "ID=$id"
+	echo "Moving $fil to $d/$ff"
+	test -d $d || mkdir $d
+	mv $fil $d/$ff
+    done
+
     cd $d
     
     pwd
     ls
-    z=`ls | awk '/.zip$/'`
-    if [ "$z" = "$ff" ]; then
-	unzip $ff 
-    fi
-    mkdir classes
+
+    for z in `find . -name  \*.zip`; do
+	unzip $z
+    done
+
+    test -d classes || mkdir classes
     find . -name \*.java | xargs javac -d classes
+    emacsclient -n `find . -name \*.java ` &
+
     cd classes
+    
+
     pp=`find * -name \*.class | sed 's/[/]/./g' `
-    p=`basename $pp .class`
-    echo $p
-    java -cp . $p | tee ../output.log
+    if [ "${pp}x" = "x" ]; then
+	echo "ERROR: Failed to compile"
+
+    else
+	main_class=""
+	for clazz in $pp; do
+	    jp=`javap $clazz | awk '/main/'`
+	    if [ "${jp}x" != "x" ]; then
+		main_class=$clazz
+	    fi
+	done
+	
+	p=`basename $main_class .class`
+	echo $p
+	java -cp . $p | tee ../output.log	    
+    fi
+
+    echo 
+    read -p  "END $f - Press enter"
 done
